<?php


namespace Cubetech\PageBuilder\Components;


/**
 * GAllery component class for pagebuilder
 *
 * @author Markus Langenegger <markus@cubetech.ch>
 * @version 1.0.0
 * @since 1.0.0
 */
class GalleryComponent extends BaseComponent
{
    
    /**
     * Title of this component
     * Generated by acf singleline field
     *
     * @var string
     */
    protected $title;
    
    /**
     * Get if Gallery has Images with links
     *
     * @var bool
     */
    protected $hasImageLink;
    
    /**
     * Get if Gallery has custom filters
     *
     * @var bool
     */
    protected $hasFilter;
    
    /**
     * Get all images with links other widtout links
     *
     * @var array
     */
    protected $gallery;
    
    /**
     * Get the string with uk-class from containers
     *
     * @var string
     */
    protected $customContainer;
    
    /**
     * Get the string with additional childs uk-child-with@
     *
     * @var string
     */
    protected $gridChilds;
    
    /**
     * Get the String with uk-flex-
     *
     * @var string
     */
    protected $startViewImage;
    
    /**
     * Get if Lightbox active
     *
     * @var bool
     */
    protected $withLightbox;
    
    /**
     * Get the Sting with uk-grid-
     *
     * @var string
     */
    protected $gridGutter;
    
    /**
     * Get the String with special uk-girds
     *
     * @var string
     */
    protected $gridGutterSpecial;
    
    
    /**
     * Get String with other overlay Color Primary
     *
     * @var string
     */
    protected $overlayColor;
    
    
    /**
     * Constructor method for this component
     * Initializes title, file and description properties
     *
     * @param int $postId
     * @param int $index
     *
     * @author Markus Langenegger <markus@cubetech.ch>
     * @since 1.0.0
     */
    public function __construct($postId, $index, $containerClass)
    {
        parent::__construct('Gallery', $postId, $index, $containerClass);
        $this->title = $this->getComponentField('gallery_title');
        $this->hasImageLink = $this->getComponentField('image_with_link');
        $this->setGallery();
        $this->hasFilter = $this->getComponentField('filter');
        $this->setCustomFilters();
        $this->createCards();
    }
    
    /**
     * Set the Gallery with images
     * ACF Gallery or Repeaterfield with images and links
     *
     * @author Markus Langenegger <markus@cubetech.ch>
     * @since 1.0.0
     */
    private function setGallery()
    {
        if ($this->hasImageLink) {
            $this->gallery = $this->getComponentRepeaterField('gallery_repeater', [
                'image',
                'link',
            ]);
        }
        else {
            $this->gallery = $this->getComponentField('gallery_images');
        }
    }
    
    /**
     * Set all Custom Filters only when is set
     *
     * @author Markus Langenegger <markus@cubetech.ch>
     * @since 1.0.0
     */
    private function setCustomFilters()
    {
        if ($this->hasFilter) {
            $this->customContainer = $this->getComponentField('ct_container');
            $this->gridChilds = $this->getComponentField('ct_grid_child_width');
            $this->startViewImage = $this->getComponentField('centered_image');
            $this->withLightbox = $this->getComponentField('with_light_box');
            $this->gridGutter = $this->getComponentField('grid_gutter');
            $this->gridGutterSpecial = $this->getComponentField('grid_gutter_special');
            $this->overlayColor = $this->getComponentField('overlay_colored_transparent');
        }
    }
    
    /**
     * Validates the component for this particular component
     *
     *
     * @return boolean
     *
     * @author Steeve Jeannin <steeve@cubetech.ch>
     * @since 1.0.0
     */
    public function isValid()
    {
        if ($this->gallery && !empty($this->gallery)) {
            return true;
        }
        else {
            return false;
        }
    }
    
}