<?php

namespace Cubetech\PageBuilder\Components;

use Cubetech\Cards\TimelineCard;
use \Cubetech\Rendering\IStringRenderable;

/**
 * History component class for pagebuilder
 *
 * @author Steeve Jeannin <steeve@cubetech.ch>
 * @version 1.0.0
 * @since 1.0.0
 */
class TimelineComponent extends BaseComponent implements IStringRenderable
{
    /**
     * Title of this component
     * Generated by acf singleline field
     *
     * @var string
     */
    protected $title;
    /**
     * General description of this component
     * Generated by acf multiline field
     *
     * @var string
     */
    protected $leadtext;
    /**
     * Year, Title and Description of history field
     * Generated from ACF repeater field
     *
     * @var string
     */
    protected $timeline;
    
    /**
     * Constructor method for this component
     * Initializes title, description and repeater properties
     *
     * @param int $postId
     * @param int $index
     *
     * @author Steeve Jeannin <steeve@cubetech.ch>
     * @since 1.0.0
     * @version 1.0.0
     */
    public function __construct($postId, $index, $containerClass)
    {
        parent::__construct('Timeline', $postId, $index, $containerClass);
        $this->title = $this->getComponentField('title');
        $this->leadtext = $this->getComponentField('leadtext');
        $this->timeline = $this->getComponentRepeaterField("timeline_repeater", [
            'timeline_year',
            'timeline_title',
            'timeline_description',
        ]);
        $this->createCards();
    }
    
    /**
     * Creates Timelinecards
     *
     * @return array <TimelineCard>
     *
     * @author Steeve Jeannin <steeve@cubetech.ch>
     * @since 1.0.0
     * @version 1.0.0
     */
    private function createCards()
    {
        $cards = [];
        foreach ($this->timeline as $entry) {
            $cards[] = new TimelineCard($this->getId(), $entry);
        }
        $this->cards = $cards;
    }
    
    /**
     * Renders all readable contents of this component as a string
     *
     * @return string
     *
     * @author Alex Scherer <alex.scherer@cubetech.ch>
     * @since 1.0.0
     * @version 1.0.0
     */
    public function renderToString()
    {
        $returnString = $this->title . ' ';
        foreach ($this->cards as $card) {
            $returnString .= $card->year . ' ';
            $returnString .= $card->title . ' ';
            $returnString .= $card->description . ' ';
        }
        return $returnString;
    }
    
    /**
     * Validates the component for this particular component
     * Both the title property and at least one history are needed
     * and therefore both must have been set
     *
     * @return boolean
     *
     * @author Steeve Jeannin <steeve@cubetech.ch>
     * @since 1.0.0
     */
    public function isValid()
    {
        if ($this->title && !empty($this->timeline)) {
            return true;
        }
        return false;
    }
}